### ISSUE TITLE
iOS14.6打开白板失败

### ISSUE THREAD

**Issue by Macrow** [netless-io/whiteboard-demo#157]
我在使用```white-web-sdk```这个库打包了二次开发的js包，提供给```webview```使用，在Android里面表现正常，在iOS14.5以及以下表现正常，但是在iOS14.6中（已测试两台设备)，第一次打开正常，第二次后面都会超时失败。

反复进行调试发现，浏览器加载完```white-web-sdk```（打包为bundle.js）后，会加载一次blob请求（看不到white-web-sdk的源代码具体位置），失败的原因是因为这一次请求超时，而无法完成白板的加载，麻烦检查一下原因。

![B132B56D-DAF9-4B15-A6F6-0789550BB56F](https://user-images.githubusercontent.com/240792/120665222-29db4b80-c4be-11eb-99c3-da5584c513ec.png)

**Comment by leavesster** [comment]
无法确认您使用的是 webview 还是 Safari，这边使用 iOS 14.6 iPhone X，在 Safari ，webview（企业微信中）连续多次访问 https://demo.netless.link ，均无法复现该问题。
在访问中，的确可以看到 blob:http 地址，不过 demo 中是 https。鉴于第一次可以访问，应该不是 http 导致的问题，不过建议可以尝试将使用 https 访问看看，可能是 iOS 14.6 的新限制也说不定。

**Comment by Macrow** [comment]
我测试了用https加载js代码，还是一样的问题。我这里有具体错误的位置，能否再看一下。

![4990D6FE-97E7-425F-B32D-C516152A2008](https://user-images.githubusercontent.com/240792/120738654-cafbed80-c522-11eb-823a-fde170890229.png)
![78F0B209-02BB-4BB5-964F-E01536EC6B72](https://user-images.githubusercontent.com/240792/120738664-cfc0a180-c522-11eb-886f-2bb097dd7f09.png)
就是在```loadScriptWithURL```里面超时发生的错误。

**Comment by Macrow** [comment]
更换了几个版本的Webview都还是一样的问题，确实不知道是哪个地方出了问题，打开官方的演示画面是正常的。

目前我暂时找到了重新刷新页面的办法解决这个问题，我先关闭这个issue。
