### ISSUE TITLE
float bar is disloated in RTL mode

### ISSUE THREAD

**Issue by Nehasoni988** [netless-io/whiteboard-demo#190]
I am using the whiteboard in RTL mode but when I use selector and select any element especially image or text in which float bar is included then the floating bar is not displaying it seems like it is positioned somewhere else.
In LTR mode it is working fine.
Could you please suggest how can I fix this?

**Comment by leavesster** [comment]
We will try to fix in feature.
You can hide it by create Room params 

```JavaScripts
var whiteWebSdk = new WhiteWebSdk({
      appIdentifier: "$APP_IDENTIFIER",
    ...{otherConfiguration},
});

whiteWebSdk.joinRoom({
    room: uuid,
    roomToken: ....,
    ....
    // make it false
    floatBar: false
}, {
    ...roomCallbacks
})
```

**Comment by Nehasoni988** [comment]
No, actually I don't want to hide this option, I want to use this because my application supports both RTL and LTR.
Can you please tell me when you can fix this?
It would be a great help.

**Comment by leavesster** [comment]
> No, actually I don't want to hide this option, I want to use this because my application supports both RTL and LTR. Can you please tell me when you can fix this? It would be a great help.

try new white-web-sdk, It should be fixed
