### ISSUE TITLE
editing the text after scaling the size will be abnormal

### ISSUE THREAD

**Issue by samchienGG** [netless-io/whiteboard-demo#222]
縮放文字後再編輯時
會觸發文字尺寸事件
我測過 flat, netless-app 皆有這個問題
所以在 demo 這裡提出

![giphy](https://user-images.githubusercontent.com/26341796/156987235-44eca41c-6dc5-4fd4-8de7-0d6a93b8878e.gif)

**Comment by leavesster** [comment]
fix in 2.16.15 for white-web-sdk
