### ISSUE TITLE
請問什麼原因會造成白板流量激增導致 crash 的問題？

### ISSUE THREAD

**Issue by samchienGG** [netless-io/whiteboard-demo#223]
從4/8開始
陸續發生流量激增導致白板 crash 這個問題
觀看上課錄影也都跟之前沒什麼異常
想詢問看看所謂流量激增
是指針對白板的行為
還是有什麼其他可能
之前都沒遇過
目前使用的版本"white-react-sdk": "2.16.10"
我會先嘗試升級到 2.16.15 看看狀況

**Comment by leavesster** [comment]
您好，这边检测到您的房间，应该是在一瞬间调用了大量的插入页面逻辑，后台抽取到特定房间有十几万个页面。服务器因此将该房间进行特殊处理，无法加入。
应该已经有 agora 商务同学邮件联系您，可以直接在对应群和邮件进行联系。
