### ISSUE TITLE
H5 zip包上传后，一直提示部署中

### ISSUE THREAD

**Issue by Matthew2015** [netless-io/whiteboard-demo#84]
![image](https://user-images.githubusercontent.com/13637773/111267573-0e9f3380-8667-11eb-9c20-2df943e5972d.png)

**Comment by l1shen** [comment]
`zip` 包资源要求的是 `h5` 课件，也就是一个可静态部署的网页, 带有 `index.html` 和静态资源的文件包
你这边上传的是
