### ISSUE TITLE
yarn dev 提示这种包找不到！看文件都是有的 ？

### ISSUE THREAD

**Issue by siYuanJun** [netless-io/whiteboard-demo#96]
![image](https://user-images.githubusercontent.com/46435703/112933457-79b23500-9152-11eb-88be-b1d6409eef63.png)
![image](https://user-images.githubusercontent.com/46435703/112934020-7ff4e100-9153-11eb-89e3-fbdc61360583.png)

**Comment by hyrious** [comment]
因为用了 workspace，你需要把 packages 里的包都 build 一下才能用
```
yarn lerna run --parallel --ignore whiteboard build:lib
```
